spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-34-200-116-132.compute-1.amazonaws.com:5432/ddohg1hk98dan1?ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory
    driver-class-name: org.postgresql.Driver
    username: xfnmxbfqznbmvi
    password: a622a751ac99b9f47ec0127039e60cb646886e08d72433c37dacda99fce9817e

logging:
  level:
    root: INFO
  file: heroapi.log
